export interface City {
  id: string;
  name: string;
  country: string;
  timezone: string;
}

export const cities: City[] = [
  { id: "1", name: "London", country: "UK", timezone: "Europe/London" },
  { id: "2", name: "New York", country: "USA", timezone: "America/New_York" },
  { id: "3", name: "Los Angeles", country: "USA", timezone: "America/Los_Angeles" },
  { id: "4", name: "San Francisco", country: "USA", timezone: "America/Los_Angeles" },
  { id: "5", name: "Tokyo", country: "Japan", timezone: "Asia/Tokyo" },
  { id: "6", name: "Sydney", country: "Australia", timezone: "Australia/Sydney" },
  { id: "7", name: "Paris", country: "France", timezone: "Europe/Paris" },
  { id: "8", name: "Berlin", country: "Germany", timezone: "Europe/Berlin" },
  { id: "9", name: "Dubai", country: "UAE", timezone: "Asia/Dubai" },
  { id: "10", name: "Singapore", country: "Singapore", timezone: "Asia/Singapore" },
  { id: "11", name: "Mumbai", country: "India", timezone: "Asia/Kolkata" },
  { id: "12", name: "Bangalore", country: "India", timezone: "Asia/Kolkata" },
  { id: "13", name: "Delhi", country: "India", timezone: "Asia/Kolkata" },
  { id: "14", name: "Toronto", country: "Canada", timezone: "America/Toronto" },
  { id: "15", name: "Chicago", country: "USA", timezone: "America/Chicago" },
  { id: "16", name: "Austin", country: "USA", timezone: "America/Chicago" },
  { id: "17", name: "Denver", country: "USA", timezone: "America/Denver" },
  { id: "18", name: "Seattle", country: "USA", timezone: "America/Los_Angeles" },
  { id: "19", name: "Boston", country: "USA", timezone: "America/New_York" },
  { id: "20", name: "Miami", country: "USA", timezone: "America/New_York" },
  { id: "21", name: "Atlanta", country: "USA", timezone: "America/New_York" },
  { id: "22", name: "Washington DC", country: "USA", timezone: "America/New_York" },
  { id: "23", name: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam" },
  { id: "24", name: "Madrid", country: "Spain", timezone: "Europe/Madrid" },
  { id: "25", name: "Rome", country: "Italy", timezone: "Europe/Rome" },
  { id: "26", name: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm" },
  { id: "27", name: "Dublin", country: "Ireland", timezone: "Europe/Dublin" },
  { id: "28", name: "Zurich", country: "Switzerland", timezone: "Europe/Zurich" },
  { id: "29", name: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen" },
  { id: "30", name: "Oslo", country: "Norway", timezone: "Europe/Oslo" },
  { id: "31", name: "Helsinki", country: "Finland", timezone: "Europe/Helsinki" },
  { id: "32", name: "Vienna", country: "Austria", timezone: "Europe/Vienna" },
  { id: "33", name: "Geneva", country: "Switzerland", timezone: "Europe/Zurich" },
  { id: "34", name: "Brussels", country: "Belgium", timezone: "Europe/Brussels" },
  { id: "35", name: "Warsaw", country: "Poland", timezone: "Europe/Warsaw" },
  { id: "36", name: "Prague", country: "Czech Republic", timezone: "Europe/Prague" },
  { id: "37", name: "Budapest", country: "Hungary", timezone: "Europe/Budapest" },
  { id: "38", name: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon" },
  { id: "39", name: "Athens", country: "Greece", timezone: "Europe/Athens" },
  { id: "40", name: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul" },
  { id: "41", name: "Moscow", country: "Russia", timezone: "Europe/Moscow" },
  { id: "42", name: "Hong Kong", country: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { id: "43", name: "Seoul", country: "South Korea", timezone: "Asia/Seoul" },
  { id: "44", name: "Beijing", country: "China", timezone: "Asia/Shanghai" },
  { id: "45", name: "Shanghai", country: "China", timezone: "Asia/Shanghai" },
  { id: "46", name: "Taipei", country: "Taiwan", timezone: "Asia/Taipei" },
  { id: "47", name: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { id: "48", name: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok" },
  { id: "49", name: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta" },
  { id: "50", name: "Manila", country: "Philippines", timezone: "Asia/Manila" },
  { id: "51", name: "Melbourne", country: "Australia", timezone: "Australia/Melbourne" },
  { id: "52", name: "Brisbane", country: "Australia", timezone: "Australia/Brisbane" },
  { id: "53", name: "Perth", country: "Australia", timezone: "Australia/Perth" },
  { id: "54", name: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland" },
  { id: "55", name: "Wellington", country: "New Zealand", timezone: "Pacific/Auckland" },
  { id: "56", name: "Tel Aviv", country: "Israel", timezone: "Asia/Jerusalem" },
  { id: "57", name: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { id: "58", name: "Karachi", country: "Pakistan", timezone: "Asia/Karachi" },
  { id: "59", name: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka" },
  { id: "60", name: "Colombo", country: "Sri Lanka", timezone: "Asia/Colombo" },
  { id: "61", name: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg" },
  { id: "62", name: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg" },
  { id: "63", name: "Cairo", country: "Egypt", timezone: "Africa/Cairo" },
  { id: "64", name: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi" },
  { id: "65", name: "Lagos", country: "Nigeria", timezone: "Africa/Lagos" },
  { id: "66", name: "Accra", country: "Ghana", timezone: "Africa/Accra" },
  { id: "67", name: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca" },
  { id: "68", name: "São Paulo", country: "Brazil", timezone: "America/Sao_Paulo" },
  { id: "69", name: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { id: "70", name: "Rio de Janeiro", country: "Brazil", timezone: "America/Sao_Paulo" },
  { id: "71", name: "Santiago", country: "Chile", timezone: "America/Santiago" },
  { id: "72", name: "Bogotá", country: "Colombia", timezone: "America/Bogota" },
  { id: "73", name: "Lima", country: "Peru", timezone: "America/Lima" },
  { id: "74", name: "Mexico City", country: "Mexico", timezone: "America/Mexico_City" },
  { id: "75", name: "Vancouver", country: "Canada", timezone: "America/Vancouver" },
  { id: "76", name: "Montreal", country: "Canada", timezone: "America/Toronto" },
  { id: "77", name: "Calgary", country: "Canada", timezone: "America/Edmonton" },
  { id: "78", name: "Honolulu", country: "USA", timezone: "Pacific/Honolulu" },
  { id: "79", name: "Anchorage", country: "USA", timezone: "America/Anchorage" },
  { id: "80", name: "Phoenix", country: "USA", timezone: "America/Phoenix" },
  { id: "81", name: "Minneapolis", country: "USA", timezone: "America/Chicago" },
  { id: "82", name: "Detroit", country: "USA", timezone: "America/Detroit" },
  { id: "83", name: "Las Vegas", country: "USA", timezone: "America/Los_Angeles" },
  { id: "84", name: "Dallas", country: "USA", timezone: "America/Chicago" },
  { id: "85", name: "Houston", country: "USA", timezone: "America/Chicago" },
  { id: "86", name: "Portland", country: "USA", timezone: "America/Los_Angeles" },
  { id: "87", name: "Ottawa", country: "Canada", timezone: "America/Toronto" },
  { id: "88", name: "Caracas", country: "Venezuela", timezone: "America/Caracas" },
  { id: "89", name: "Guadalajara", country: "Mexico", timezone: "America/Mexico_City" },
  { id: "90", name: "Monterrey", country: "Mexico", timezone: "America/Monterrey" },
  { id: "91", name: "Lahore", country: "Pakistan", timezone: "Asia/Karachi" },
  { id: "92", name: "Ho Chi Minh City", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { id: "93", name: "Hanoi", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { id: "94", name: "Yangon", country: "Myanmar", timezone: "Asia/Yangon" },
  { id: "95", name: "Kathmandu", country: "Nepal", timezone: "Asia/Kathmandu" },
  { id: "96", name: "Islamabad", country: "Pakistan", timezone: "Asia/Karachi" },
  { id: "97", name: "Tashkent", country: "Uzbekistan", timezone: "Asia/Tashkent" },
  { id: "98", name: "Almaty", country: "Kazakhstan", timezone: "Asia/Almaty" },
  { id: "99", name: "Baku", country: "Azerbaijan", timezone: "Asia/Baku" },
  { id: "100", name: "Tbilisi", country: "Georgia", timezone: "Asia/Tbilisi" },
  { id: "101", name: "Yerevan", country: "Armenia", timezone: "Asia/Yerevan" },
  { id: "102", name: "Kyiv", country: "Ukraine", timezone: "Europe/Kyiv" },
  { id: "103", name: "Minsk", country: "Belarus", timezone: "Europe/Minsk" },
  { id: "104", name: "Bucharest", country: "Romania", timezone: "Europe/Bucharest" },
  { id: "105", name: "Sofia", country: "Bulgaria", timezone: "Europe/Sofia" },
  { id: "106", name: "Zagreb", country: "Croatia", timezone: "Europe/Zagreb" },
  { id: "107", name: "Sarajevo", country: "Bosnia", timezone: "Europe/Sarajevo" },
  { id: "108", name: "Belgrade", country: "Serbia", timezone: "Europe/Belgrade" },
  { id: "109", name: "Riga", country: "Latvia", timezone: "Europe/Riga" },
  { id: "110", name: "Tallinn", country: "Estonia", timezone: "Europe/Tallinn" },
  { id: "111", name: "Vilnius", country: "Lithuania", timezone: "Europe/Vilnius" },
].sort((a, b) => a.name.localeCompare(b.name));

export function getLocalCity(): City | undefined {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return cities.find((c) => c.timezone === tz);
  } catch (e) {
    return undefined;
  }
}
